export const cities = [
    'Abriaquí',
	'Acacías',
	'Acandí',
	'Acevedo',
	'Achí',
	'Agrado',
	'Agua de Dios',
	'Aguachica',
	'Aguada',
	'Aguadas',
	'Aguazul',
	'Agustín Codazzi',
	'Aipe',
	'Albania(CAQUETÁ)',
	'Albania(LA GUAJIRA)',
	'Albania(SANTANDER)',
	'Albán',
	'Albán (San José)',
	'Alcalá',
	'Alejandria',
	'Algarrobo',
	'Algeciras',
	'Almaguer',
	'Almeida',
	'Alpujarra',
	'Altamira',
	'Alto Baudó (Pie de Pato)',
	'Altos del Rosario',
	'Alvarado',
	'Amagá',
	'Amalfi',
	'Ambalema',
	'Anapoima',
	'Ancuya',
	'Andalucía',
	'Andes',
	'Angelópolis',
	'Angostura',
	'Anolaima',
	'Anorí',
	'Anserma',
	'Ansermanuevo',
	'Anzoátegui',
	'Anzá',
	'Apartadó',
	'Apulo',
	'Apía',
	'Aquitania',
	'Aracataca',
	'Aranzazu',
	'Aratoca',
	'Arauca',
	'Arauquita',
	'Arbeláez',
	'Arboleda (Berruecos)',
	'Arboledas',
	'Arboletes',
	'Arcabuco',
	'Arenal',
	'Argelia(ANTIOQUIA)',
	'Argelia(CAUCA)',
	'Argelia(VALLE DEL CAUCA)',
	'Ariguaní (El Difícil)',
	'Arjona',
	'Armenia(ANTIOQUIA)',
	'Armenia(QUINDIO)',
	'Armero (Guayabal)',
	'Arroyohondo',
	'Astrea',
	'Ataco',
	'Atrato (Yuto)',
	'Ayapel',
	'Bagadó',
	'Bahía Solano (Mútis)',
	'Bajo Baudó (Pizarro)',
	'Balboa(CAUCA)',
	'Balboa(RISARALDA)',
	'Baranoa',
	'Baraya',
	'Barbacoas',
	'Barbosa(ANTIOQUIA)',
	'Barbosa(SANTANDER)',
	'Barichara',
	'Barranca de Upía',
	'Barrancabermeja',
	'Barrancas',
	'Barranco de Loba',
	'Barranquilla',
	'Becerríl',
	'Belalcázar',
	'Bello',
	'Belmira',
	'Beltrán',
	'Belén(BOYACÁ)',
	'Belén(NARIÑO)',
	'Belén de Bajirá',
	'Belén de Umbría',
	'Belén de los Andaquíes',
	'Berbeo',
	'Betania',
	'Beteitiva',
	'Betulia(ANTIOQUIA)',
	'Betulia(SANTANDER)',
	'Bituima',
	'Boavita',
	'Bochalema',
	'Bogotá D.C.',
	'Bojacá',
	'Bojayá (Bellavista)',
	'Bolívar(ANTIOQUIA)',
	'Bolívar(CAUCA)',
	'Bolívar(SANTANDER)',
	'Bolívar(VALLE DEL CAUCA)',
	'Bosconia',
	'Boyacá',
	'Briceño(ANTIOQUIA)',
	'Briceño(BOYACÁ)',
	'Bucaramanga',
	'Bucarasica',
	'Buenaventura',
	'Buenavista(BOYACÁ)',
	'Buenavista(CÓRDOBA)',
	'Buenavista(QUINDIO)',
	'Buenavista(SUCRE)',
	'Buesaco',
	'Buga',
	'Bugalagrande',
	'Burítica',
	'Busbanza',
	'Cabrera(CUNDINAMARCA)',
	'Cabrera(SANTANDER)',
	'Cabuyaro',
	'Cachipay',
	'Caicedo',
	'Caicedonia',
	'Caimito',
	'Cajamarca',
	'Cajibío',
	'Cajicá',
	'Calamar(BOLÍVAR)',
	'Calamar(GUAVIARE)',
	'Calarcá',
	'Caldas(ANTIOQUIA)',
	'Caldas(BOYACÁ)',
	'Caldono',
	'California',
	'Calima (Darién)',
	'Caloto',
	'Calí',
	'Campamento',
	'Campo de la Cruz',
	'Campoalegre',
	'Campohermoso',
	'Canalete',
	'Candelaria(ATLÁNTICO)',
	'Candelaria(VALLE DEL CAUCA)',
	'Cantagallo',
	'Cantón de San Pablo',
	'Caparrapí',
	'Capitanejo',
	'Caracolí',
	'Caramanta',
	'Carcasí',
	'Carepa',
	'Carmen de Apicalá',
	'Carmen de Carupa',
	'Carmen de Viboral',
	'Carmen del Darién (CURBARADÓ)',
	'Carolina',
	'Cartagena',
	'Cartagena del Chairá',
	'Cartago',
	'Carurú',
	'Casabianca',
	'Castilla la Nueva',
	'Caucasia',
	'Cañasgordas',
	'Cepita',
	'Cereté',
	'Cerinza',
	'Cerrito',
	'Cerro San Antonio',
	'Chachaguí',
	'Chaguaní',
	'Chalán',
	'Chaparral',
	'Charalá',
	'Charta',
	'Chigorodó',
	'Chima',
	'Chimichagua',
	'Chimá',
	'Chinavita',
	'Chinchiná',
	'Chinácota',
	'Chinú',
	'Chipaque',
	'Chipatá',
	'Chiquinquirá',
	'Chiriguaná',
	'Chiscas',
	'Chita',
	'Chitagá',
	'Chitaraque',
	'Chivatá',
	'Chivolo',
	'Choachí',
	'Chocontá',
	'Chámeza',
	'Chía',
	'Chíquiza',
	'Chívor',
	'Cicuco',
	'Cimitarra',
	'Circasia',
	'Cisneros',
	'Ciénaga (BOYACÁ)',
	'Ciénaga (MAGDALENA)',
	'Ciénaga de Oro',
	'Clemencia',
	'Cocorná',
	'Coello',
	'Cogua',
	'Colombia',
	'Colosó (Ricaurte)',
	'Colón',
	'Colón (Génova)',
	'Concepción (ANTIOQUIA)',
	'Concepción (SANTANDER)',
	'Concordia (ANTIOQUIA)',
	'Concordia (MAGDALENA)',
	'Condoto',
	'Confines',
	'Consaca',
	'Contadero',
	'Contratación',
	'Convención',
	'Copacabana',
	'Coper',
	'Cordobá',
	'Corinto',
	'Coromoro',
	'Corozal',
	'Corrales',
	'Cota',
	'Cotorra',
	'Covarachía',
	'Coveñas',
	'Coyaima',
	'Cravo Norte',
	'Cuaspud (Carlosama)',
	'Cubarral',
	'Cubará',
	'Cucaita',
	'Cucunubá',
	'Cucutilla',
	'Cuitiva',
	'Cumaral',
	'Cumaribo',
	'Cumbal',
	'Cumbitara',
	'Cunday',
	'Curillo',
	'Curití',
	'Curumaní',
	'Cáceres',
	'Cáchira',
	'Cácota',
	'Cáqueza',
	'Cértegui',
	'Cómbita',
	'Córdoba (BOLÍVAR)',
	'Córdoba (NARIÑO)',
	'Cúcuta',
	'Dabeiba',
	'Dagua',
	'Dibulla',
	'Distracción',
	'Dolores',
	'Don Matías',
	'Dos Quebradas',
	'Duitama',
	'Durania',
	'Ebéjico',
	'El Bagre',
	'El Banco',
	'El Cairo',
	'El Calvario',
	'El Carmen (NORTE DE SANTANDER)',
	'El Carmen (SANTANDER)',
	'El Carmen de Atrato',
	'El Carmen de Bolívar',
	'El Castillo',
	'El Cerrito',
	'El Charco',
	'El Cocuy',
	'El Colegio',
	'El Copey',
	'El Doncello',
	'El Dorado',
	'El Dovio',
	'El Espino',
	'El Guacamayo',
	'El Guamo',
	'El Molino',
	'El Paso',
	'El Paujil',
	'El Peñol',
	'El Peñon (BOLÍVAR)',
	'El Peñon (SANTANDER)',
	'El Peñón (CUNDINAMARCA)',
	'El Piñon',
	'El Playón',
	'El Retorno',
	'El Retén',
	'El Roble',
	'El Rosal',
	'El Rosario',
	'El Tablón de Gómez',
	'El Tambo (CAUCA)',
	'El Tambo (NARIÑO)',
	'El Tarra',
	'El Zulia',
	'El Águila',
	'Elías',
	'Encino',
	'Enciso',
	'Entrerríos',
	'Envigado',
	'Espinal',
	'Facatativá',
	'Falan',
	'Filadelfia',
	'Filandia',
	'Firavitoba',
	'Flandes',
	'Florencia (CAQUETÁ)',
	'Florencia (CAUCA)',
	'Floresta',
	'Florida',
	'Floridablanca',
	'Florián',
	'Fonseca',
	'Fortúl',
	'Fosca',
	'Francisco Pizarro',
	'Fredonia',
	'Fresno',
	'Frontino',
	'Fuente de Oro',
	'Fundación',
	'Funes',
	'Funza',
	'Fusagasugá',
	'Fómeque',
	'Fúquene',
	'Gachalá',
	'Gachancipá',
	'Gachantivá',
	'Gachetá',
	'Galapa',
	'Galeras (Nueva Granada)',
	'Galán',
	'Gama',
	'Gamarra',
	'Garagoa',
	'Garzón',
	'Gigante',
	'Ginebra',
	'Giraldo',
	'Girardot',
	'Girardota',
	'Girón',
	'Gonzalez',
	'Gramalote',
	'Granada (ANTIOQUIA)',
	'Granada (CUNDINAMARCA)',
	'Granada (META)',
	'Guaca',
	'Guacamayas',
	'Guacarí',
	'Guachavés',
	'Guachené',
	'Guachetá',
	'Guachucal',
	'Guadalupe (ANTIOQUIA)',
	'Guadalupe (HUILA)',
	'Guadalupe (SANTANDER)',
	'Guaduas',
	'Guaitarilla',
	'Gualmatán',
	'Guamal (MAGDALENA)',
	'Guamal (META)',
	'Guamo',
	'Guapota',
	'Guapí',
	'Guaranda',
	'Guarne',
	'Guasca',
	'Guatapé',
	'Guataquí',
	'Guatavita',
	'Guateque',
	'Guavatá',
	'Guayabal de Siquima',
	'Guayabetal',
	'Guayatá',
	'Guepsa',
	'Guicán',
	'Gutiérrez',
	'Guática',
	'Gámbita',
	'Gámeza',
	'Génova',
	'Gómez Plata',
	'Hacarí',
	'Hatillo de Loba',
	'Hato',
	'Hato Corozal',
	'Hatonuevo',
	'Heliconia',
	'Herrán',
	'Herveo',
	'Hispania',
	'Hobo',
	'Honda',
	'Ibagué',
	'Icononzo',
	'Iles',
	'Imúes',
	'Inzá',
	'Inírida',
	'Ipiales',
	'Isnos',
	'Istmina',
	'Itagüí',
	'Ituango',
	'Izá',
	'Jambaló',
	'Jamundí',
	'Jardín',
	'Jenesano',
	'Jericó (ANTIOQUIA)',
	'Jericó (BOYACÁ)',
	'Jerusalén',
	'Jesús María',
	'Jordán',
	'Juan de Acosta',
	'Junín',
	'Juradó',
	'La Apartada y La Frontera',
	'La Argentina',
	'La Belleza',
	'La Calera',
	'La Capilla',
	'La Ceja',
	'La Celia',
	'La Cruz',
	'La Cumbre',
	'La Dorada',
	'La Esperanza',
	'La Estrella',
	'La Florida',
	'La Gloria',
	'La Jagua de Ibirico',
	'La Jagua del Pilar',
	'La Llanada',
	'La Macarena',
	'La Merced',
	'La Mesa',
	'La Montañita',
	'La Palma',
	'La Paz',
	'La Paz (Robles)',
	'La Peña',
	'La Pintada',
	'La Plata',
	'La Playa',
	'La Primavera',
	'La Salina',
	'La Sierra',
	'La Tebaida',
	'La Tola',
	'La Unión (ANTIOQUIA)',
	'La Unión (NARIÑO)',
	'La Unión (SUCRE)',
	'La Unión (VALLE DEL CAUCA)',
	'La Uvita',
	'La Vega (CAUCA)',
	'La Vega (CUNDINAMARCA)',
	'La Victoria (BOYACÁ)',
	'La Victoria (CALDAS)',
	'La Victoria (VALLE DEL CAUCA)',
	'La Virginia',
	'Labateca',
	'Labranzagrande',
	'Landázuri',
	'Lebrija',
	'Leiva',
	'Lejanías',
	'Lenguazaque',
	'Leticia',
	'Liborina',
	'Linares',
	'Lloró',
	'Lorica',
	'Los Córdobas',
	'Los Palmitos',
	'Los Patios',
	'Los Santos',
	'Lourdes',
	'Luruaco',
	'Lérida',
	'Líbano',
	'López (Micay)',
	'Macanal',
	'Macaravita',
	'Maceo',
	'Machetá',
	'Madrid',
	'Magangué',
	'Magüi (Payán)',
	'Mahates',
	'Maicao',
	'Majagual',
	'Malambo',
	'Mallama (Piedrancha)',
	'Manatí',
	'Manaure',
	'Manaure Balcón del Cesar',
	'Manizales',
	'Manta',
	'Manzanares',
	'Maní',
	'Mapiripan',
	'Margarita',
	'Marinilla',
	'Maripí',
	'Mariquita',
	'Marmato',
	'Marquetalia',
	'Marsella',
	'Marulanda',
	'María la Baja',
	'Matanza',
	'Medellín',
	'Medina',
	'Medio Atrato',
	'Medio Baudó',
	'Medio San Juan (ANDAGOYA)',
	'Melgar',
	'Mercaderes',
	'Mesetas',
	'Milán',
	'Miraflores (BOYACÁ)',
	'Miraflores (GUAVIARE)',
	'Miranda',
	'Mistrató',
	'Mitú',
	'Mocoa',
	'Mogotes',
	'Molagavita',
	'Momil',
	'Mompós',
	'Mongua',
	'Monguí',
	'Moniquirá',
	'Montebello',
	'Montecristo',
	'Montelíbano',
	'Montenegro',
	'Monteria',
	'Monterrey',
	'Morales (BOLÍVAR)',
	'Morales (CAUCA)',
	'Morelia',
	'Morroa',
	'Mosquera (CUNDINAMARCA)',
	'Mosquera (NARIÑO)',
	'Motavita',
	'Moñitos',
	'Murillo',
	'Murindó',
	'Mutatá',
	'Mutiscua',
	'Muzo',
	'Málaga',
	'Nariño (ANTIOQUIA)',
	'Nariño (CUNDINAMARCA)',
	'Nariño (NARIÑO)',
	'Natagaima',
	'Nechí',
	'Necoclí',
	'Neira',
	'Neiva',
	'Nemocón',
	'Nilo',
	'Nimaima',
	'Nobsa',
	'Nocaima',
	'Norcasia',
	'Norosí',
	'Novita',
	'Nueva Granada',
	'Nuevo Colón',
	'Nunchía',
	'Nuquí',
	'Nátaga',
	'Obando',
	'Ocamonte',
	'Ocaña',
	'Oiba',
	'Oicatá',
	'Olaya',
	'Olaya Herrera',
	'Onzaga',
	'Oporapa',
	'Orito',
	'Orocué',
	'Ortega',
	'Ospina',
	'Otanche',
	'Ovejas',
	'Pachavita',
	'Pacho',
	'Padilla',
	'Paicol',
	'Pailitas',
	'Paime',
	'Paipa',
	'Pajarito',
	'Palermo',
	'Palestina (CALDAS)',
	'Palestina (HUILA)',
	'Palmar',
	'Palmar de Varela',
	'Palmas del Socorro',
	'Palmira',
	'Palmito',
	'Palocabildo',
	'Pamplona',
	'Pamplonita',
	'Pandi',
	'Panqueba',
	'Paratebueno',
	'Pasca',
	'Patía (El Bordo)',
	'Pauna',
	'Paya',
	'Paz de Ariporo',
	'Paz de Río',
	'Pedraza',
	'Pelaya',
	'Pensilvania',
	'Peque',
	'Pereira',
	'Pesca',
	'Peñol',
	'Piamonte',
	'Pie de Cuesta',
	'Piedras',
	'Piendamó',
	'Pijao',
	'Pijiño',
	'Pinchote',
	'Pinillos',
	'Piojo',
	'Pisva',
	'Pital',
	'Pitalito',
	'Pivijay',
	'Planadas',
	'Planeta Rica',
	'Plato',
	'Policarpa',
	'Polonuevo',
	'Ponedera',
	'Popayán',
	'Pore',
	'Potosí',
	'Pradera',
	'Prado',
	'Providencia (NARIÑO)',
	'Providencia (ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA)',
	'Pueblo Bello',
	'Pueblo Nuevo',
	'Pueblo Rico',
	'Pueblorrico',
	'Puebloviejo',
	'Puente Nacional',
	'Puerres',
	'Puerto Asís',
	'Puerto Berrío',
	'Puerto Boyacá',
	'Puerto Caicedo',
	'Puerto Carreño',
	'Puerto Colombia',
	'Puerto Concordia',
	'Puerto Escondido',
	'Puerto Gaitán',
	'Puerto Guzmán',
	'Puerto Leguízamo',
	'Puerto Libertador',
	'Puerto Lleras',
	'Puerto López',
	'Puerto Nare',
	'Puerto Nariño',
	'Puerto Parra',
	'Puerto Rico (CAQUETÁ)',
	'Puerto Rico (META)',
	'Puerto Rondón',
	'Puerto Salgar',
	'Puerto Santander',
	'Puerto Tejada',
	'Puerto Triunfo',
	'Puerto Wilches',
	'Pulí',
	'Pupiales',
	'Puracé (Coconuco)',
	'Purificación',
	'Purísima',
	'Pácora',
	'Páez',
	'Páez (Belalcazar)',
	'Páramo',
	'Quebradanegra',
	'Quetame',
	'Quibdó',
	'Quimbaya',
	'Quinchía',
	'Quipama',
	'Quipile',
	'Ragonvalia',
	'Ramiriquí',
	'Recetor',
	'Regidor',
	'Remedios',
	'Remolino',
	'Repelón',
	'Restrepo (META)',
	'Restrepo (VALLE DEL CAUCA)',
	'Retiro',
	'Ricaurte (CUNDINAMARCA)',
	'Ricaurte (NARIÑO)',
	'Rio Negro',
	'Rioblanco',
	'Riofrío',
	'Riohacha',
	'Risaralda',
	'Rivera',
	'Roberto Payán (San José)',
	'Roldanillo',
	'Roncesvalles',
	'Rondón',
	'Rosas',
	'Rovira',
	'Ráquira',
	'Río Iró',
	'Río Quito',
	'Río Sucio',
	'Río Viejo',
	'Río de oro',
	'Ríonegro',
	'Ríosucio',
	'Sabana de Torres',
	'Sabanagrande',
	'Sabanalarga (ANTIOQUIA)',
	'Sabanalarga (ATLÁNTICO)',
	'Sabanalarga (CASANARE)',
	'Sabanas de San Angel (SAN ANGEL)',
	'Sabaneta',
	'Saboyá',
	'Sahagún',
	'Saladoblanco',
	'Salamina (CALDAS)',
	'Salamina (MAGDALENA)',
	'Salazar',
	'Saldaña',
	'Salento',
	'Salgar',
	'Samacá',
	'Samaniego',
	'Samaná',
	'Sampués',
	'San Agustín',
	'San Alberto',
	'San Andrés',
	'San Andrés Sotavento',
	'San Andrés de Cuerquía',
	'San Antero',
	'San Antonio',
	'San Antonio de Tequendama',
	'San Benito',
	'San Benito Abad',
	'San Bernardo (CUNDINAMARCA)',
	'San Bernardo (NARIÑO)',
	'San Bernardo del Viento',
	'San Calixto',
	'San Carlos (ANTIOQUIA)',
	'San Carlos (CÓRDOBA)',
	'San Carlos de Guaroa',
	'San Cayetano (CUNDINAMARCA)',
	'San Cayetano (NORTE DE SANTANDER)',
	'San Cristobal',
	'San Diego',
	'San Eduardo',
	'San Estanislao',
	'San Fernando',
	'San Francisco (ANTIOQUIA)',
	'San Francisco (CUNDINAMARCA)',
	'San Francisco (PUTUMAYO)',
	'San Gíl',
	'San Jacinto',
	'San Jacinto del Cauca',
	'San Jerónimo',
	'San Joaquín',
	'San José',
	'San José de Miranda',
	'San José de Montaña',
	'San José de Pare',
	'San José de Uré',
	'San José del Fragua',
	'San José del Guaviare',
	'San José del Palmar',
	'San Juan de Arama',
	'San Juan de Betulia',
	'San Juan de Nepomuceno',
	'San Juan de Pasto',
	'San Juan de Río Seco',
	'San Juan de Urabá',
	'San Juan del Cesar',
	'San Juanito',
	'San Lorenzo',
	'San Luis',
	'San Luís',
	'San Luís de Gaceno',
	'San Luís de Palenque',
	'San Marcos',
	'San Martín (CESAR)',
	'San Martín (META)',
	'San Martín de Loba',
	'San Mateo',
	'San Miguel (SANTANDER)',
	'San Miguel (PUTUMAYO)',
	'San Miguel de Sema',
	'San Onofre',
	'San Pablo (BOLÍVAR)',
	'San Pablo (NARIÑO)',
	'San Pablo de Borbur',
	'San Pedro (ANTIOQUIA)',
	'San Pedro (SUCRE)',
	'San Pedro (VALLE DEL CAUCA)',
	'San Pedro de Cartago',
	'San Pedro de Urabá',
	'San Pelayo',
	'San Rafael',
	'San Roque',
	'San Sebastián',
	'San Sebastián de Buenavista',
	'San Vicente',
	'San Vicente del Caguán',
	'San Vicente del Chucurí',
	'San Zenón',
	'Sandoná',
	'Santa Ana',
	'Santa Bárbara (ANTIOQUIA)',
	'Santa Bárbara (SANTANDER)',
	'Santa Bárbara (Iscuandé)',
	'Santa Bárbara de Pinto',
	'Santa Catalina',
	'Santa Fé de Antioquia',
	'Santa Genoveva de Docorodó',
	'Santa Helena del Opón',
	'Santa Isabel',
	'Santa Lucía',
	'Santa Marta',
	'Santa María (BOYACÁ)',
	'Santa María (HUILA)',
	'Santa Rosa (BOLÍVAR)',
	'Santa Rosa (CAUCA)',
	'Santa Rosa de Cabal',
	'Santa Rosa de Osos',
	'Santa Rosa de Viterbo',
	'Santa Rosa del Sur',
	'Santa Rosalía',
	'Santa Sofía',
	'Santana',
	'Santander de Quilichao',
	'Santiago (NORTE DE SANTANDER)',
	'Santiago (PUTUMAYO)',
	'Santo Domingo',
	'Santo Tomás',
	'Santuario (ANTIOQUIA)',
	'Santuario (RISARALDA)',
	'Sapuyes',
	'Saravena',
	'Sardinata',
	'Sasaima',
	'Sativanorte',
	'Sativasur',
	'Segovia',
	'Sesquilé',
	'Sevilla',
	'Siachoque',
	'Sibaté',
	'Sibundoy',
	'Silos',
	'Silvania',
	'Silvia',
	'Simacota',
	'Simijaca',
	'Simití',
	'Sincelejo',
	'Sincé',
	'Sipí',
	'Sitionuevo',
	'Soacha',
	'Soatá',
	'Socha',
	'Socorro',
	'Socotá',
	'Sogamoso',
	'Solano',
	'Soledad',
	'Solita',
	'Somondoco',
	'Sonsón',
	'Sopetrán',
	'Soplaviento',
	'Sopó',
	'Sora',
	'Soracá',
	'Sotaquirá',
	'Sotara (Paispamba)',
	'Sotomayor (Los Andes)',
	'Suaita',
	'Suan',
	'Suaza',
	'Subachoque',
	'Sucre (CAUCA)',
	'Sucre (SANTANDER)',
	'Sucre (SUCRE)',
	'Suesca',
	'Supatá',
	'Supía',
	'Suratá',
	'Susa',
	'Susacón',
	'Sutamarchán',
	'Sutatausa',
	'Sutatenza',
	'Suárez (CAUCA)',
	'Suárez (TOLIMA)',
	'Sácama',
	'Sáchica',
	'Tabio',
	'Tadó',
	'Talaigua Nuevo',
	'Tamalameque',
	'Tame',
	'Taminango',
	'Tangua',
	'Taraira',
	'Tarazá',
	'Tarqui',
	'Tarso',
	'Tasco',
	'Tauramena',
	'Tausa',
	'Tello',
	'Tena',
	'Tenerife',
	'Tenjo',
	'Tenza',
	'Teorama',
	'Teruel',
	'Tesalia',
	'Tibacuy',
	'Tibaná',
	'Tibasosa',
	'Tibirita',
	'Tibú',
	'Tierralta',
	'Timaná',
	'Timbiquí',
	'Timbío',
	'Tinjacá',
	'Tipacoque',
	'Tiquisio (Puerto Rico)',
	'Titiribí',
	'Toca',
	'Tocaima',
	'Tocancipá',
	'Toguí',
	'Toledo (ANTIOQUIA)',
	'Toledo (NORTE DE SANTANDER)',
	'Tolú',
	'Tolú Viejo',
	'Tona',
	'Topagá',
	'Topaipí',
	'Toribío',
	'Toro',
	'Tota',
	'Totoró',
	'Trinidad',
	'Trujillo',
	'Tubará',
	'Tuchín',
	'Tulúa',
	'Tumaco',
	'Tunja',
	'Tunungua',
	'Turbaco',
	'Turbaná',
	'Turbo',
	'Turmequé',
	'Tuta',
	'Tutasá',
	'Támara',
	'Támesis',
	'Túquerres',
	'Ubalá',
	'Ubaque',
	'Ubaté',
	'Ulloa',
	'Une',
	'Unguía',
	'Unión Panamericana (ÁNIMAS)',
	'Uramita',
	'Uribe',
	'Uribia',
	'Urrao',
	'Urumita',
	'Usiacuri',
	'Valdivia',
	'Valencia',
	'Valle de San José',
	'Valle de San Juan',
	'Valle del Guamuez',
	'Valledupar',
	'Valparaiso (ANTIOQUIA)',
	'Valparaiso (CAQUETÁ)',
	'Vegachí',
	'Venadillo',
	'Venecia',
	'Venecia (Ospina Pérez)',
	'Ventaquemada',
	'Vergara',
	'Versalles',
	'Vetas',
	'Viani',
	'Vigía del Fuerte',
	'Vijes',
	'Villa Caro',
	'Villa Rica',
	'Villa de Leiva',
	'Villa del Rosario',
	'Villagarzón',
	'Villagómez',
	'Villahermosa',
	'Villamaría',
	'Villanueva (BOLÍVAR)',
	'Villanueva (LA GUAJIRA)',
	'Villanueva (SANTANDER)',
	'Villanueva (CASANARE)',
	'Villapinzón',
	'Villarrica',
	'Villavicencio',
	'Villavieja',
	'Villeta',
	'Viotá',
	'Viracachá',
	'Vista Hermosa',
	'Viterbo',
	'Vélez',
	'Yacopí',
	'Yacuanquer',
	'Yaguará',
	'Yalí',
	'Yarumal',
	'Yolombó',
	'Yondó (Casabe)',
	'Yopal',
	'Yotoco',
	'Yumbo',
	'Zambrano',
	'Zapatoca',
	'Zapayán (PUNTA DE PIEDRAS)',
	'Zaragoza',
	'Zarzal',
	'Zetaquirá',
	'Zipacón',
	'Zipaquirá',
	'Zona Bananera (PRADO - SEVILLA)',
	'Ábrego',
	'Íquira',
	'Úmbita',
	'Útica'
]