/*
acescoElementsProtection: true
activitiesAsSocialReason: true
additionalSafetyMeasures: true
annex6: true
authoritiesReporting: true
confidentiality: true
containersIntegity: true
contingencyPlan: true
continuousCommunication: true
dissuasionElements: true
documentationAndSystemsConfidentiality: true
economicActivityEvidence: true
illicitActivitiesAbsence: true
inadequateProposals: true
inadequateProposalsWhat: "Sexo por dinero"
legalRequirementsAndRegulations: true
manifest: true
minimumSafetyRequirements: true
perimetersControl: true
physicalAccessControls: true
physicalSecurityAgreements: true
physicalSecurityGuarantee: true
productSpecifications: true
protectionProgram: true
qualityCertifications: true
recommendations: true
relationshipRequirements: true
safetyData: true
sanitaryRegulations: true
secureFacilities: true
securityAgreements: true
securityDocuments: true
securityService: true
selectionProgram: true
shippingDocumentation: true
storageAndTransportIntegrity: true
sustainabilityReport: true
technicalStandards: true
trainingPrograms: true
warningDevices: true*/
